---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
    channel: rubocop-0-50
    config:
      file: .rubocop.yml
  reek:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- "uspec/**/*"
