version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x cc-test-reporter
      - run:
          name: Prepare CodeClimate reporter
          command: ./cc-test-reporter before-build
      - run:
          name: Uspec tests
          command: bundle exec uspec
      - run:
          name: Report coverage to CodeClimate 
          command: ./cc-test-reporter after-build --coverage-input-type simplecov
